### ISSUE TITLE
Prompt flow endpoint not working.

### ISSUE THREAD

**Issue by AlpCastel** [garrytrinder/msteams-azure-search-openai-demo#12]
I've changed the Endpoint URL to the [Azure AI Studio Prompt Flow Endpoint](https://learn.microsoft.com/en-us/azure/ai-studio/how-to/flow-deploy?tabs=azure-studio) but I won't get any response back... am I missing something here?

**Comment by garrytrinder** [comment]
The sample is designed to only be used with the API endpoint provided by the [Azure Search OpenAI Demo](https://github.com/Azure-Samples/azure-search-openai-demo). You will need to adapt the sample for it to work with other APIs.
