### ISSUE TITLE
Directly integrate all Azure services for this to work so this can work independently. 

### ISSUE THREAD

**Issue by Moin-Ud-Din** [garrytrinder/msteams-azure-search-openai-demo#5]
This issue is for a: (mark with an x)
- [] bug report
- [x] feature request

If possible, we would be able to deploy teams app without using App Service by Azure as if I want my Bot to just work for Teams than why do I need to creat an WebApp as well which won't be used by the people.

**Comment by garrytrinder** [comment]
A web server is essential for a bot to function properly in Teams. It enables the bot to receive and send messages, process user input, access relevant data, and perform tasks. Without a web server, the bot would not be able to connect to the Bot Framework or the Teams client.

**Comment by Moin-Ud-Din** [comment]
@garrytrinder thanks for the explanation.
