### ISSUE TITLE
Why is not using existing Azure Services which have been deployed with azure search

### ISSUE THREAD

**Issue by M0inUddin** [garrytrinder/msteams-azure-search-openai-demo#6]
Like in my case it have deployed all these 
![image](https://github.com/garrytrinder/msteams-azure-search-openai-demo/assets/61883188/449dedce-5b76-4731-856c-047297e9a185)
shouldn't it share Storage and as in my previous chat with you, you told that it needs Azure Search App to be deployed but then why is it  using a new app as well.

**Comment by garrytrinder** [comment]
This sample was designed to be a standalone app and so uses its own Azure resources.

The resources required for the sample are:

- Azure Bot Service, acts as a message broker to send messages to and from Microsoft Teams and bot code
- Azure Web App, used as the bot messaging endpoint and bot logic
- Storage Account (Blob Container), stores conversation state and history

These resources are defined in 

- [infra\azure.bicep](https://github.dev/garrytrinder/msteams-azure-search-openai-demo/blob/c6d36e035eb420bd88a321d172a4c018b1ccc905/infra/azure.bicep)
  - Azure Web App
  - Storage Account
- [infra\botRegistration\azurebot.bicep](https://github.dev/garrytrinder/msteams-azure-search-openai-demo/blob/c6d36e035eb420bd88a321d172a4c018b1ccc905/infra/botRegistration/azurebot.bicep)
  - Azure Bot Service

In the `teamsapp.yml` file there are two tasks that provision these resources and also deploy the code.

- [arm/deploy](https://github.dev/garrytrinder/msteams-azure-search-openai-demo/blob/c6d36e035eb420bd88a321d172a4c018b1ccc905/teamsapp.yml#L94)
- [azureAppService/zipDeploy](https://github.dev/garrytrinder/msteams-azure-search-openai-demo/blob/c6d36e035eb420bd88a321d172a4c018b1ccc905/teamsapp.yml#L31)

If you want to reuse existing resources, then I would suggest updating these files to your needs.
