### ISSUE TITLE
Bot not responding

### ISSUE THREAD

**Issue by M0inUddin** [garrytrinder/msteams-azure-search-openai-demo#7]
![image](https://github.com/garrytrinder/msteams-azure-search-openai-demo/assets/61883188/fa83c0b2-be3d-4dcc-a22c-3ed1d83c220c)
So, I tried two different repo yours and the forked one by tawfek both gave me different results
### Your repo,
- When ran both locally and from dev environment I saw no welcome card and when I send a message no response of error or anything in chat window or in terminal
### tawfek repo
- When ran both locally and from dev environment I did saw a welcome card and did get a response though in error but when I google this error didn't find any solutions there.

**Comment by garrytrinder** [comment]
Apologies for the delay. This is mostly likely caused by a response returned from the API that the bot code cannot transform. Have you made any changes to the API?

**Comment by garrytrinder** [comment]
Thanks, can you confirm that the front end web app is working correctly?

The `getChatResponse` function is making the same call to the backend API that the web app does, which seems to be returning an `Internal Server Error`.

**Comment by garrytrinder** [comment]
I just re-deployed the frontend and backend from the latest source and noticed that the payload sent in the request is now different to what is being sent from the bot, it's possible that the API has been updated which is causing this issue.

If you inspect the request sent to the API when you submit a message in the chat using Dev Tools, do you see similar to the below?

![image](https://github.com/garrytrinder/msteams-azure-search-openai-demo/assets/11563347/4fd14eff-f919-4d2c-ade4-0651603bae41)

I'll need to take a further look into this.

**Comment by garrytrinder** [comment]
As thought, the API has certainly changed, the request and response payloads are very different.

I've made some progress this morning and have the request and response working in a local branch.

![image](https://github.com/garrytrinder/msteams-azure-search-openai-demo/assets/11563347/fdb88647-545a-4580-91d5-cdcaf7bbb2cf)

I'm going to spend some time on the card logic tomorrow, so that the citations and references are represented similar to the way the web app displays the inline references and to remove the duplicate Citations.

I'll keep you updated on my progress.

**Comment by garrytrinder** [comment]
Here are the new inline references and removed duplicates.

![image](https://github.com/garrytrinder/msteams-azure-search-openai-demo/assets/11563347/4f1c47bc-73f8-40fa-a7d9-6e8ed4bc3369)

The code is a bit rough so needs some tidying up so I'll so that tomorrow.

**Comment by garrytrinder** [comment]
I've just pushed the updates to the repo. 

@UsamaMoinJavid are you able to pull down the latest changes and confirm that all is now working OK?

**Comment by garrytrinder** [comment]
Thanks for confirming @UsamaMoinJavid 👍 

Please do raise an issue if you run into any problems or have any feedback.

**Comment by pvejayan** [comment]
@garrytrinder it seem that we have encountered the same issue as Moin Uddin, when we run the app locally it works fine this based on the previous code (https://github.com/Azure-Samples/azure-search-openai-demo). when the app is provisoned and deployed to the team store and published and run, none of the cards are loading and the bot is not responding. i have attaached the logs from the bot below 


</head><body><div id="content"><div class="content-container"><h3>HTTP Error 404.0 - Not Found</h3><h4>The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul> 	<li>The directory or file specified does not exist on the Web server.</li> 	




your help in undersatnding the problem will be much appriciated. what is conerning is the bot feel like it does not contain any app refrences .

**Comment by M0inUddin** [comment]
Bot not working when deployed to Azure Services

**Comment by pvejayan** [comment]
@garrytrinder  I have got the deployment working with no auth, while building the app we have noticed the node compiled lib is addressing to server.js . once we have changed the rules in the web.config the published teams app was communicating to the bot services then forwarding to the frontend of the web app  .

**Comment by garrytrinder** [comment]
Thanks for the comments @M0inUddin @pvejayan I'll take a look later today.

**Comment by garrytrinder** [comment]
Thanks for investigating @pvejayan ❤️

The `web.config` files was referencing `index.js` when it should have been `server.js`.

I've just merged a PR with a fix. 

Thanks again, appreciate you trying out this sample.
